-- 상품
CREATE TABLE KOSMO_PRODUCT(
	KPNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPCOMPANY VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER
   ,KPPRICE NUMBER
   ,KPDESC VARCHAR2(2000)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_PRODUCT;

SELECT  /*+ INDEX_DESC(A SYS_C0011100) */
        NVL(MAX(SUBSTR(A.KPNUM, -4)), 0) + 1  KPNUM 
FROM    KOSMO_PRODUCT A;

-- SYS_C0011100
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_PRODUCT');

-- 카트
DROP TABLE KOSMO_CART;
CREATE TABLE KOSMO_CART(
    KCNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER   
   ,KPPRICE NUMBER
   ,KPPRICESUM NUMBER   
   ,KPNUM VARCHAR2(20) 
   ,KMNUM VARCHAR2(20)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_CART ORDER BY 1;

SELECT  /*+ INDEX_DESC(A SYS_C0011101) */
        NVL(MAX(SUBSTR(A.KCNUM, -4)), 0) + 1  KCNUM 
FROM    KOSMO_CART A;

-- SYS_C0011101
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_CART');

UPDATE KOSMO_CART 
SET DELETEYN='Y', UPDATEDATE=SYSDATE 
WHERE  KCNUM = 'C202205160004';

SELECT * FROM KOSMO_CART;

-- 주문

-- 회원
DROP TABLE KOSMO_MEMBER;
CREATE TABLE KOSMO_MEMBER(
    KMNUM VARCHAR2(20) PRIMARY KEY
   ,KMID VARCHAR2(20)
   ,KMPW VARCHAR2(300)
   ,KMNAME VARCHAR2(100)
   ,KMHP VARCHAR2(16)  
   ,KMEMAIL VARCHAR2(200)   
   ,KMZONE VARCHAR2(6)
   ,KMROAD VARCHAR2(200)
   ,KMROAD2 VARCHAR2(200) 
   ,KMJIBUN VARCHAR2(200)
   ,KMIMAGE VARCHAR2(200)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE     
);

SELECT * FROM KOSMO_MEMBER;

SELECT  /*+ INDEX_DESC(A SYS_C0011102) */
        NVL(MAX(SUBSTR(A.KMNUM, -4)), 0) + 1  KMNUM 
FROM    KOSMO_MEMBER A;

-- SYS_C0011102
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_MEMBER');

INSERT INTO KOSMO_MEMBER ( KMNUM, KMID, KMPW, 
                            KMNAME, KMHP, KMEMAIL, 
                            KMZONE, KMROAD, KMROAD2, 
                            KMJIBUN, KMIMAGE, DELETEYN, 
                            INSERTDATE, UPDATEDATE) 
                VALUES( '111', '111', '111', 
                        '111', '01011111111', '111@gmail.com', 
                        '111', '111', '111', 
                        '111', '111', 'Y', 
                        SYSDATE, SYSDATE); 
ROLLBACK;

SELECT A.KMNUM KMNUM ,A.KMID KMID ,A.KMPW KMPW ,A.KMNAME KMNAME ,A.KMHP KMHP ,A.KMEMAIL KMEMAIL ,A.KMZONE KMZONE ,A.KMROAD KMROAD ,A.KMROAD2 KMROAD2 ,A.KMJIBUN KMJIBUN ,A.KMIMAGE KMIMAGE ,A.DELETEYN DELETEYN ,TO_CHAR(A.INSERTDATE, 'YYYY-MM-DD') INSERTDATE ,TO_CHAR(A.UPDATEDATE, 'YYYY-MM-DD') UPDATEDATE FROM KOSMO_MEMBER A WHERE A.DELETEYN = 'Y' ORDER BY 1 DESC;


SELECT A.KMID KMID ,A.KMPW KMPW FROM KOSMO_MEMBER A WHERE A.DELETEYN = 'Y' AND A.KMID = '1111' AND A.KMPW = '1111';

-- 게시판
CREATE TABLE KOSMO_BOARD(
     KBNUM VARCHAR2(20) PRIMARY KEY 
    ,KBSUBJECT VARCHAR2(200)
    ,KBNAME VARCHAR2(100)
    ,KBCONTENT VARCHAR2(2000) 
    ,KBFILE VARCHAR2(200) 
    ,KBPW VARCHAR2(300)
    ,DELETEYN VARCHAR2(1) 
    ,INSERTDATE DATE 
    ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_BOARD;

SELECT  /*+ INDEX_DESC(A SYS_C0011103) */
        NVL(MAX(SUBSTR(A.KBNUM, -4)), 0) + 1  KBNUM 
FROM    KOSMO_BOARD A;

-- SYS_C0011103
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_BOARD');

