-- 상품
CREATE TABLE KOSMO_PRODUCT(
	KPNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPCOMPANY VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER
   ,KPPRICE NUMBER
   ,KPDESC VARCHAR2(2000)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_PRODUCT;

SELECT  /*+ INDEX_DESC(A SYS_C0012636) */
        NVL(MAX(SUBSTR(A.KPNUM, -4)), 0) + 1  KPNUM 
FROM    KOSMO_PRODUCT A;

-- SYS_C0012636
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_PRODUCT');

-- 카트
DROP TABLE KOSMO_CART;
CREATE TABLE KOSMO_CART(
    KCNUM VARCHAR2(20) PRIMARY KEY
   ,KPID VARCHAR2(20)
   ,KPNAME VARCHAR2(200)
   ,KPFILE VARCHAR2(200)
   ,KPCNT NUMBER   
   ,KPPRICE NUMBER
   ,KPPRICESUM NUMBER   
   ,KPNUM VARCHAR2(20) 
   ,KMNUM VARCHAR2(20)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_CART;

UPDATE KOSMO_CART SET DELETEYN = 'N', UPDATEDATE = SYSDATE WHERE KCNUM = 'C202205220007';
ROLLBACK;

SELECT  /*+ INDEX_DESC(A SYS_C0012663) */
        NVL(MAX(SUBSTR(A.KCNUM, -4)), 0) + 1  KCNUM 
FROM    KOSMO_CART A;

-- SYS_C0012663
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_CART');

-- 주문
DROP TABLE KOSMO_ORDER;
CREATE TABLE KOSMO_ORDER (   
     KONUM VARCHAR2(20) PRIMARY KEY -- 상품주문번호 
    ,KPNUM VARCHAR2(20)
    ,KPID VARCHAR2(20)
    ,KPNAME VARCHAR2(200)    
    ,KPCNT NUMBER   
    ,KPPRICE NUMBER
    ,KPPRICESUM NUMBER  
    ,KMNUM VARCHAR2(20) 
    ,KMID VARCHAR2(20) 
    ,KMNAME VARCHAR2(100)
    ,KMHP VARCHAR2(16)  
    ,KMEMAIL VARCHAR2(200) 
    ,KODEIVARY VARCHAR2(10) -- 배송방법 01, 02, 03
    ,KOZONE VARCHAR2(6)
    ,KOROAD VARCHAR2(200)
    ,KOROAD2 VARCHAR2(200) 
    ,KOJIBUN VARCHAR2(200)
    ,DELETEYN VARCHAR2(1)
    ,INSERTDATE DATE
    ,UPDATEDATE DATE   
);

SELECT * FROM KOSMO_ORDER;

SELECT  /*+ INDEX_DESC(A SYS_C0012826) */
        NVL(MAX(SUBSTR(A.KONUM, -4)), 0) + 1  KONUM 
FROM    KOSMO_ORDER A;

-- SYS_C0012826
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_ORDER');

-- 카드결제 
DROP TABLE KOSMO_CARD;
CREATE TABLE KOSMO_CARD (

);


-- 회원
DROP TABLE KOSMO_MEMBER;
CREATE TABLE KOSMO_MEMBER(
    KMNUM VARCHAR2(20) PRIMARY KEY
   ,KMID VARCHAR2(20)
   ,KMPW VARCHAR2(300)
   ,KMNAME VARCHAR2(100)
   ,KMHP VARCHAR2(16)  
   ,KMEMAIL VARCHAR2(200)   
   ,KMZONE VARCHAR2(6)
   ,KMROAD VARCHAR2(200)
   ,KMROAD2 VARCHAR2(200) 
   ,KMJIBUN VARCHAR2(200)
   ,KMIMAGE VARCHAR2(200)
   ,DELETEYN VARCHAR2(1)
   ,INSERTDATE DATE
   ,UPDATEDATE DATE     
);

SELECT * FROM KOSMO_MEMBER;

SELECT  /*+ INDEX_DESC(A SYS_C0012665) */
        NVL(MAX(SUBSTR(A.KMNUM, -4)), 0) + 1  KMNUM 
FROM    KOSMO_MEMBER A;

-- SYS_C0012665
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_MEMBER');

INSERT INTO KOSMO_MEMBER ( KMNUM, KMID, KMPW, 
                            KMNAME, KMHP, KMEMAIL, 
                            KMZONE, KMROAD, KMROAD2, 
                            KMJIBUN, KMIMAGE, DELETEYN, 
                            INSERTDATE, UPDATEDATE) 
                VALUES( '111', '111', '111', 
                        '111', '01011111111', '111@gmail.com', 
                        '111', '111', '111', 
                        '111', '111', 'Y', 
                        SYSDATE, SYSDATE); 
ROLLBACK;

SELECT A.KMNUM KMNUM ,A.KMID KMID ,A.KMPW KMPW ,A.KMNAME KMNAME ,A.KMHP KMHP ,A.KMEMAIL KMEMAIL ,A.KMZONE KMZONE ,A.KMROAD KMROAD ,A.KMROAD2 KMROAD2 ,A.KMJIBUN KMJIBUN ,A.KMIMAGE KMIMAGE ,A.DELETEYN DELETEYN ,TO_CHAR(A.INSERTDATE, 'YYYY-MM-DD') INSERTDATE ,TO_CHAR(A.UPDATEDATE, 'YYYY-MM-DD') UPDATEDATE FROM KOSMO_MEMBER A WHERE A.DELETEYN = 'Y' ORDER BY 1 DESC;


SELECT A.KMID KMID ,A.KMPW KMPW FROM KOSMO_MEMBER A WHERE A.DELETEYN = 'Y' AND A.KMID = '1111' AND A.KMPW = '1111';

-- 게시판
CREATE TABLE KOSMO_BOARD(
     KBNUM VARCHAR2(20) PRIMARY KEY 
    ,KBSUBJECT VARCHAR2(200)
    ,KBNAME VARCHAR2(100)
    ,KBCONTENT VARCHAR2(2000) 
    ,KBFILE VARCHAR2(200) 
    ,KBPW VARCHAR2(300)
    ,DELETEYN VARCHAR2(1) 
    ,INSERTDATE DATE 
    ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_BOARD;

SELECT  /*+ INDEX_DESC(A SYS_C0012694) */
        NVL(MAX(SUBSTR(A.KBNUM, -4)), 0) + 1  KBNUM 
FROM    KOSMO_BOARD A;

-- SYS_C0012694
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_BOARD');

-- 댓글
DROP TABLE KOSMO_RBOARD;
CREATE TABLE KOSMO_RBOARD (
    RKBNUM VARCHAR2(20) PRIMARY KEY 
   ,KBNUM VARCHAR2(20) 
   ,RKBNAME VARCHAR2(100)
   ,RKBCONTENT VARCHAR2(300)    
   ,DELETEYN VARCHAR2(1) 
   ,INSERTDATE DATE 
);

SELECT * FROM KOSMO_RBOARD;

SELECT  /*+ INDEX_DESC(A SYS_C0012770) */
        NVL(MAX(SUBSTR(A.RKBNUM, -4)), 0) + 1  RKBNUM 
FROM    KOSMO_RBOARD A;

-- SYS_C0012770
SELECT A.TABLE_NAME, A.COLUMN_NAME, A.INDEX_NAME
FROM   ALL_IND_COLUMNS A
WHERE  A.TABLE_NAME IN ('KOSMO_RBOARD');

-- RKBCONTENT 컬럼 사이즈 300 에서 200 으로 변경
ALTER TABLE KOSMO_RBOARD MODIFY (RKBCONTENT VARCHAR2(200));
DESC KOSMO_RBOARD;

-- 게시판 좋아요 
DROP TABLE KOSMO_BOARD_LIKE;
CREATE TABLE KOSMO_BOARD_LIKE (
     KBLNUM NUMBER PRIMARY KEY 
    ,KMNUM VARCHAR2(20)
    ,KBNUM VARCHAR2(20)
    ,KBLIKE_CNT_1 NUMBER DEFAULT 0 
    ,KBLIKE_CNT_2 NUMBER DEFAULT 0 
    ,KBLIKE_CNT_3 NUMBER DEFAULT 0 
    ,KBLIKE_CNT_4 NUMBER DEFAULT 0 
    ,KBLIKE_CNT_5 NUMBER DEFAULT 0 
    ,KBLIKE_CNT_6 NUMBER DEFAULT 0 
    ,DELETEYN VARCHAR2(1) 
    ,INSERTDATE DATE 
    ,UPDATEDATE DATE
);

SELECT * FROM KOSMO_BOARD_LIKE;
ROLLBACK;
INSERT INTO KOSMO_BOARD_LIKE (KBLNUM, KMNUM, KBNUM, DELETEYN, INSERTDATE, UPDATEDATE )VALUES('2', 'M11', 'B1', 'Y', SYSDATE, SYSDATE);

SELECT * FROM KOSMO_BOARD_LIKE A WHERE A.DELETEYN = 'Y' AND A.KMNUM = 'M202205230005' AND A.KBNUM = 'B0001'; 
