--  20220509
SELECT ROWID FROM EMP;
SELECT ROUND(STDDEV(SAL),2) FROM EMP;

-- GROUP BY를 사용하여 부서별 평균 급여 출력하기
SELECT AVG(SAL), DEPTNO
FROM EMP 
GROUP BY DEPTNO;

SELECT AVG(A.SAL) AS SAL
                                , B.DNAME AS DNAME
FROM EMP A, DEPT B
WHERE A.DEPTNO=B.DEPTNO
GROUP BY B.DNAME;

-- 부서번호의 부서명을 출력하시오.
SELECT A.DEPTNO, B.DNAME
FROM EMP A, DEPT B
WHERE A.DEPTNO=B.DEPTNO
GROUP BY A.DEPTNO, B.DNAME;

-- 사원의 직책의 종류를 구하세요.
SELECT DISTINCT(A.JOB) AS DISTINCTJOB
FROM EMP A;

-- GROUP BY가 더 빠르다.
SELECT A.JOB
FROM EMP A
GROUP BY A.JOB;

SELECT A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A, DEPT B
WHERE A.DEPTNO=B.DEPTNO
GROUP BY A.DEPTNO, B.DNAME, B.DEPTNO;


-- EMP 테이블과 DEPT 테이블을 조회하여 각 부서별 급여 편차가 가장 큰
-- 부서 이름을 소수점 첫 째자리까지만 출력시키시오.
SELECT B.DNAME
FROM(SELECT DEPTNO
                ,ROUND(STDDEV(SAL), 1) AS DSAL
                FROM EMP
                GROUP BY DEPTNO
                ORDER BY DSAL DESC) A, DEPT B
WHERE A.DEPTNO=B.DEPTNO
AND ROWNUM<=1;




-- 부서에 있는 직책별 평균 급여로 정렬하기
SELECT*FROM EMP;

SELECT DEPTNO, JOB, SAL FROM EMP;

-- 부서별로 나누어 봅시다.
SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO;

-- 부서별로 직책 보기
SELECT DEPTNO, JOB
FROM EMP
GROUP BY DEPTNO, JOB;

-- 부서별로 평균 급여 보기
SELECT DEPTNO, JOB, AVG(SAL) AS ASAL
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- + 부서이름, 부서번호, 직책, 연봉 집어 넣기
-- 부서에 있는 직책별 평균 급여로 정렬하기
SELECT  A.DEPTNO, B.DEPTNO, B.DNAME, A.JOB, AVG(A.SAL)
FROM EMP A, DEPT B
WHERE A.DEPTNO(+)=B.DEPTNO
GROUP BY A.DEPTNO, B.DEPTNO, B.DNAME, A.JOB
ORDER BY A.DEPTNO, A.JOB;



