SELECT EMPNO, ENAME, JOB, MGR
FROM EMP;

-- 20220513 
-- self join
-- EMP 테이블의 사원의 상관의 이름을 조회해보세요
SELECT*FROM EMP;

-- JOIN으로 조회해보기

-- ORACLE SYNTAX
SELECT A.EMPNO, A.ENAME, A.MGR
                ,B.EMPNO
                , B.ENAME AS MANAGER
FROM EMP A, EMP B
WHERE A.MGR=B.EMPNO;

-- ANSI SYNTAX
SELECT A.EMPNO, A.ENAME, A.MGR, B.ENAME AS MANAGER
FROM EMP A
JOIN EMP B ON A.MGR=B.EMPNO;

-- USING SUBQUERY 
-- CHECK
SELECT MGR FROM EMP WHERE ENAME='FORD';
-- 7566 : FORD 사원의 상관사원 번호
SELECT ENAME FROM EMP WHERE EMPNO='7566';
-- 사원의 이름이 JONES가 나와야 한다.

SELECT*FROM EMP WHERE MGR=
(SELECT MGR FROM EMP WHERE ENAME='FORD');

SELECT*FROM EMP WHERE EMPNO=
(SELECT MGR FROM EMP WHERE ENAME='FORD');

-- 상사(매니저)가 없는 사원을 구하시오
SELECT A.EMPNO, A.ENAME, A.MGR
                ,B.EMPNO
                , B.ENAME AS MANAGER
FROM EMP A, EMP B
WHERE A.MGR=B.EMPNO(+);
-- KING

-- CHECK
SELECT MGR FROM EMP WHERE ENAME='KING';
-- null

-- MGR null 체크

SELECT ENAME
FROM EMP
WHERE MGR IS NULL;

-- USING SUBQUERY
SELECT EMPNO,ENAME,NVL2(MGR, 'Y', 'N') AS CMGR FROM EMP;

SELECT ENAME
FROM (SELECT EMPNO,ENAME,NVL2(MGR, 'Y', 'N') AS CMGR FROM EMP)
WHERE CMGR='N';

SELECT*FROM EMP WHERE ENAME='KING';

-- 상사가 있는 직원들을 조회해보세요
SELECT EMPNO, ENAME, MGR FROM EMP;

SELECT EMPNO, ENAME, MGR FROM EMP
WHERE MGR IS NOT NULL;

SELECT ENAME, SAL FROM EMP;
SELECT*FROM SALGRADE;

-- 700이상 1200 미만 1급
SELECT COUNT(EMPNO) FROM EMP
WHERE SAL>=700
AND SAL<1200;
-- 3명

-- 1201이상 1400미만 2급
SELECT COUNT(EMPNO)
FROM EMP
WHERE SAL>=1201
AND SAL<1400;
-- 3명

-- 1401이상 2000미만 3급
SELECT COUNT(EMPNO)
FROM EMP
WHERE SAL>1401
AND SAL<2000;
-- 2명

-- 2001이상 3000미만 4급
SELECT COUNT(EMPNO)
FROM EMP
WHERE SAL>2001
AND SAL<3000;
-- 3명

-- 3001이상 9999미만 5급
SELECT COUNT(EMPNO)
FROM EMP
WHERE SAL>3001
AND SAL<9999;
-- 1명

SELECT*FROM SALGRADE;

-- 각 사원의 급여가 어느 등급에 속하는지 찾아보세요
SELECT *
FROM EMP A, SALGRADE B
WHERE  A.SAL>=B.LOSAL
AND A.SAL<=B.HISAL;





