-- 20220525 YYS

-- INDEX : 색인 
-- 테이블 만들어서 채번로직 만ㄷ르어보기
CREATE TABLE INDEX_TEST_1(
    INDEX_1 NUMBER PRIMARY KEY
);

SELECT*FROM INDEX_TEST_1;

SELECT MAX(INDEX_1) FROM INDEX_TEST_1;

SELECT /*+ INDEX_DESC(A SYS_C0013191)   */ NVL(MAX(INDEX_1), 0)+1 AS INUM  FROM INDEX_TEST_1;


-- 실무에서는 항상 인덱스를 먼저 조회해야 한다.
SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('INDEX_TEST_1');
--TABLE_NAME :  INDEX_TEST_1
-- INDEX_NAME : SYS_C0013191
--COLUMN_NAME : INDEX_1

-- PK 생성시 자동으로 시스템에서 시스템을 인덱스를 생성하기 때문에
-- 사용자 정의로 인덱스를 생성할 수 있다.

-- 인덱스 생성하기
CREATE TABLE T2(
    T2_1 NUMBER,
    T2_2 VARCHAR2(10)
);

SELECT*FROM T2;

-- 단일 인덱스
CREATE  INDEX_T2_T2_1 ON T2(T2_1);
-- ORA-00901: CREATE 명령어가 부적합합니다
-- 00901. 00000 -  "invalid CREATE command"

-- 결합 인덱스
CREATE INDEX INDEX_T2_T2_1_T2_2 ON T2(T2_1, T2_2);

SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN ('T2');
-- 인덱스가 생긴 것을 볼 수 있다.

/*
사전 정의된 롤
CONNECT 롤(ROLE)
    -- Release 9.0버전
    ALTER SESSION
    CREATE CLUSTER
    CREATE SEQUENCE
    CREATE SESSION
    CREATE SYNONYM
    CREATE TABLE
    CREATE VIEW
    -- Release 11.2 버전
    CREATE SESSION
RESOURCE 롤(ROLE)
    CREATE CLUSTER
    CREATE PROCEDURE
    CREATE SEQUENCE
    CREATE TABLE
    CREATE TRIGGER
*/
    
    


