CREATE TABLE MVC_BOARD(
	 BNUM		VARCHAR2(20) PRIMARY KEY 
	,BSUBJECT	VARCHAR2(100)	NOT NULL
	,BWRITER	VARCHAR2(30)
	,BPW		VARCHAR2(300)
	,BMEMO		VARCHAR2(2000)
	,DELETEYN	VARCHAR2(1)		NOT NULL
	,INSERTDATE	DATE
	,UPDATEDATE DATE
);

-- 인텍스
-- SYS_C0012473
SELECT TABLE_NAME, COLUMN_NAME, INDEX_NAME
FROM   USER_IND_COLUMNS
WHERE  TABLE_NAME IN ('MVC_BOARD');

-- 일반 게시판 채번 B0001
-- /*+ 힌트(HINT) */
-- HINT : 힌트 : 오라클에서 사용하는 기술 : SELECT 할 때 조회 속도를 향상 시키기 위해서 
SELECT 
    /*+ INDEX_DESC(A SYS_C0012473) */
    NVL(MAX(SUBSTR(A.BNUM, -4)), 0) + 1 AS COMMON  
FROM MVC_BOARD A;

DESC MVC_BOARD;
/*
이름         널?       유형             
---------- -------- -------------- 
BNUM       NOT NULL VARCHAR2(20)   
BSUBJECT   NOT NULL VARCHAR2(100)  
BWRITER             VARCHAR2(30)   
BPW                 VARCHAR2(300)  
BMEMO               VARCHAR2(2000) 
DELETEYN   NOT NULL VARCHAR2(1)    
INSERTDATE          DATE           
UPDATEDATE          DATE           
*/

SELECT*FROM MVC_BOARD
WHERE DELETEYN='Y';
commit;

/*
INSERT INTO MVC_BOARD(
 BNUM
	,BSUBJECT
	,BWRITER
	,BPW
	,BMEMO
	,DELETEYN
	,INSERTDATE
	,UPDATEDATE
)
VALUES (
'B0001'
	,'01'
	,'01'
	,'01'
	,'01'
	,'Y'
	,SYSDATE
	,SYSDATE
);

ROLLBACK;
*/

DESC MVC_BOARD;

SELECT
                 A.BNUM          AS BNUM
                ,A.BSUBJECT AS BSUBJECT
                ,A.BWRITER AS BWRITER
                ,A.BPW AS BPW
                ,A.BMEMO AS BMEMO
                ,A.DELETEYN AS DELETEYN
                ,TO_CHAR(TO_DATE(A.INSERTDATE), 'YYYY-MM-DD') AS INSERTDATE
                ,TO_CHAR(TO_DATE(A.UPDATEDATE), 'YYYY-MM-DD') AS UPDATEDATE
FROM MVC_BOARD A
WHERE A.DELETEYN='Y'
ORDER BY BNUM DESC;

-- 수정하기
SELECT BSUBJECT, BMEMO
FROM MVC_BOARD
WHERE DELETEYN='Y'
AND BNUM='B0001';

UPDATE MVC_BOARD
SET BSUBJECT='수정'
        ,BMEMO='수정한 메모'
        ,UPDATEDATE=SYSDATE
WHERE DELETEYN='Y'
AND BNUM='B0001';

ROLLBACK;

-- 삭제하기
SELECT BSUBJECT, BMEMO
FROM MVC_BOARD
WHERE DELETEYN='Y'
AND BNUM='B0003';

UPDATE MVC_BOARD
SET DELETEYN='N'
WHERE DELETEYN='Y'
AND BNUM='B0003';

SELECT BNUM, DELETEYN
FROM MVC_BOARD
WHERE BNUM='B0003';

ROLLBACK;


SELECT COUNT(A.BNUM) NCNT
FROM MVC_BOARD A
WHERE DELETEYN='Y'
AND A.BNUM='B0013'
AND A.BPW='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';


