CREATE TABLE KOSMO_PRODUCT(
        MNUM  VARCHAR2(20) PRIMARY KEY
        ,MID  VARCHAR2(20)
        ,MCNT  VARCHAR2(20)
        ,MNAME  VARCHAR2(300)
        ,MPRICE  VARCHAR2(20)
        ,MDES  VARCHAR2(300)
        ,MCOM  VARCHAR2(300)
        ,MIMG  VARCHAR2(300)
        ,MINSERTDATE  DATE   NOT NULL
        ,MUPDATEDATE  DATE  NOT NULL
        ,MDELETEYN  VARCHAR(1) NOT NULL
);

SELECT*FROM KOSMO_PRODUCT;


