CREATE TABLE BAR_CHART(
    YYYY VARCHAR2(20) PRIMARY KEY 
   ,SALES VARCHAR2(20)
   ,COSTS   VARCHAR2(20)
);

INSERT INTO BAR_CHART VALUES('2014',1000, 400);
INSERT INTO BAR_CHART VALUES('2015',1170, 460);
INSERT INTO BAR_CHART VALUES('2016',660, 1120);
INSERT INTO BAR_CHART VALUES('2017',1030, 540);

SELECT * FROM BAR_CHART;

COMMIT;

CREATE TABLE PIE_CHART(
    TASK VARCHAR2(100) PRIMARY KEY,
    HOURSDAY VARCHAR2(10)
)
SELECT * FROM PIE_CHART;

INSERT INTO PIE_CHART VALUES ('Work', 11);
INSERT INTO PIE_CHART VALUES ('Eat', 2);
INSERT INTO PIE_CHART VALUES ('Commute', 2);
INSERT INTO PIE_CHART VALUES ('Watch TV', 2);
INSERT INTO PIE_CHART VALUES ('Sleep', 7);
COMMIT;